# Generated by Django 2.2.3 on 2019-07-28 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rated', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.ManyToManyField(help_text='What is the moved rated?', to='manager.Rating'),
        ),
    ]
