# Generated by Django 2.2.3 on 2019-07-29 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20190728_0331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='director',
            options={},
        ),
        migrations.AddField(
            model_name='movie',
            name='image_url',
            field=models.CharField(default='', max_length=2083),
            preserve_default=False,
        ),
    ]
